[package]
name = "module_roots"
version = "0.1.0"
edition = "2021"

[dependencies]
arbutil = { path = "../../arbutil/" }
prover = { path = "../../prover/" }
eyre = "0.6.5"
structopt = "0.3.23"

[workspace]
