[package]
name = "bench"
version = "0.1.0"
edition = "2021"

[lib]
name = "bench"
path = "src/lib.rs"

[[bin]]
name = "benchbin"
path = "src/bin.rs"

[dependencies]
hex = { version = "0.4.3", features = ["serde"] }
eyre = "0.6.5"
prover = { path = "../prover" }
arbutil = { path = "../arbutil" }
clap = { version = "4.4.8", features = ["derive"] }
gperftools = { version = "0.2.0", optional = true }
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = "1.0.67"
serde_with = { version = "3.8.1", features = ["base64"] }

[features]
counters = []
cpuprof = ["gperftools"]
heapprof = ["gperftools", "gperftools/heap"]
