[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "target-cpu=mvp",
]

[target.wasm32-wasi]
rustflags = [
  "-C", "target-cpu=mvp",
]

[unstable]
build-std = ["core", "panic_abort", "alloc", "std"]
