name: Submodule Pin Check

on:
  pull_request:
    branches: [ master ]
    types: [synchronize, opened, reopened]

jobs:
  submodule-pin-check:
    name: Submodule Pin Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Check all submodules are ancestors of origin/HEAD or configured branch
        run: ${{ github.workspace }}/.github/workflows/submodule-pin-check.sh

